### ISSUE TITLE
Crear las Entidades y DB Context

### ISSUE THREAD

**Issue by TETvega** [TETvega/PROYECTO-POO-IIPACK-2024#1]
Crear las entidades necesarias para el proyecto y configurar el DbContext para interactuar con la base de datos.
## Criterios de Aceptación:
Las entidades deben estar definidas con todas las propiedades necesarias.
El **DbContext debe estar configurado correctamente**.
### Tareas:
 - Crear la entidad Usuario.
 - Crear la entidad Producto.
 - Crear la entidad Evento.
 - Crear la entidad DetalleEvento.
 - Crear la entidad ReservaProducto.
 - Configurar el DbContext.
 - Categoria de productos
 - Categoria de Usuario Consumidor
 - Probar la conexión con la base de datos.

**Comment by annerh3** [comment]
Okay. Ya está.

**Comment by annerh3** [comment]
Okay. ya Está.
