### ISSUE TITLE
Crear los DTOs de las Entidades

### ISSUE THREAD

**Issue by TETvega** [TETvega/PROYECTO-POO-IIPACK-2024#2]
#1 

### Criterios de Aceptación:
- Los DTOs deben estar definidos para cada entidad.
- Los DTOs deben incluir todas las propiedades necesarias para la transferencia de datos.
- 
### Tareas:
 - Crear el DTO para Usuario.
 - Crear el DTO para Producto.
 - Crear el DTO para Evento.
 - Crear el DTO para DetalleEvento.
 - Crear el DTO para ReservaProducto.(tabla de reservas del producto fecha, cantidad)
 - Crear el DTO de Categoria Producto
 - Crear el Dto de Categoria de Usuario Consumidor
 - Crear el Dto de Comentario

**Comment by annerh3** [comment]
ready to go!
