### ISSUE TITLE
Agregar los IServices y Services

### ISSUE THREAD

**Issue by TETvega** [TETvega/PROYECTO-POO-IIPACK-2024#4]
Crear los archivos de Servicio para cada una de las entidades necesarias, así como crear la lógica de cada uno de ellos. 
## Crear los servicios primarios 👍 
- Categoría de Cliente
- Categoría de Producto
- Categorías necesarias

### Crear el servicio de Notas de evento
un evento puede tener muchas notas, compuestas de un Título, id del evento al que pertenece y una descripción opcional

## Crear los servicios y lógica de las demás Entidades 💯 
La entidad de evento crea los registros de detalle de evento y la de reserva de productos tener en cuenta esto

**Comment by annerh3** [comment]
we're ready to go, pookie
